/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newemployeeapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x15037835
 */
public class EmployeeGUI extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeGUI
     */
    private String type,dept,name;
    private int empId,hours,confDialog;
    private double salary, budget, rate;
        
    private ArrayList<Employee> empList,searchList;
    
    public EmployeeGUI() {
        initComponents();
        
        name ="";
        empId =0;
        type = "";
        dept = "";
        salary=0.0;
        budget=0.0;
        hours=0;
        rate=0.0;
        
        if(getData() == null) {
            empList = new ArrayList<Employee>();
        } else {
            empList = getData();
        }
        salaryTxt.setVisible(false);
        deptTxt.setVisible(false);
        budgetTxt.setVisible(false);
        
        hoursTxt.setVisible(false);
        rateTxt.setVisible(false);
        
        salaryLbl.setVisible(false);
        deptLbl.setVisible(false);
        budgetLbl.setVisible(false);
        
        hoursLbl.setVisible(false);
        rateLbl.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empBtnGroup = new javax.swing.ButtonGroup();
        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmployeeRd = new javax.swing.JRadioButton();
        EngineerRd = new javax.swing.JRadioButton();
        ConsultantRd = new javax.swing.JRadioButton();
        ManagerRd = new javax.swing.JRadioButton();
        DirectorRd = new javax.swing.JRadioButton();
        salaryLbl = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        deptLbl = new javax.swing.JLabel();
        deptTxt = new javax.swing.JTextField();
        budgetLbl = new javax.swing.JLabel();
        budgetTxt = new javax.swing.JTextField();
        hoursLbl = new javax.swing.JLabel();
        hoursTxt = new javax.swing.JTextField();
        rateLbl = new javax.swing.JLabel();
        rateTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        viewAllBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Type");

        empBtnGroup.add(EmployeeRd);
        EmployeeRd.setText("Employee");
        EmployeeRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeRdActionPerformed(evt);
            }
        });

        empBtnGroup.add(EngineerRd);
        EngineerRd.setText("Engineer");
        EngineerRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerRdActionPerformed(evt);
            }
        });

        empBtnGroup.add(ConsultantRd);
        ConsultantRd.setText("Consultant");
        ConsultantRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultantRdActionPerformed(evt);
            }
        });

        empBtnGroup.add(ManagerRd);
        ManagerRd.setText("Manager");
        ManagerRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerRdActionPerformed(evt);
            }
        });

        empBtnGroup.add(DirectorRd);
        DirectorRd.setText("Director");
        DirectorRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectorRdActionPerformed(evt);
            }
        });

        salaryLbl.setText("Salary");

        salaryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryTxtActionPerformed(evt);
            }
        });

        deptLbl.setText("Dept");

        deptTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptTxtActionPerformed(evt);
            }
        });

        budgetLbl.setText("Budget");

        budgetTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetTxtActionPerformed(evt);
            }
        });

        hoursLbl.setText("Hours");

        hoursTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursTxtActionPerformed(evt);
            }
        });

        rateLbl.setText("Rate");

        rateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTxtActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        viewAllBtn.setText("View All");
        viewAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("To delete enter Employe name AND id:");

        jLabel10.setText("To search Employe enter name OR id:");

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeRd)
                            .addComponent(EngineerRd)
                            .addComponent(ConsultantRd)
                            .addComponent(ManagerRd)
                            .addComponent(DirectorRd)
                            .addComponent(jLabel9)
                            .addComponent(deleteBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(salaryLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(deptLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(budgetLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(budgetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hoursLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoursTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewAllBtn))
                    .addComponent(jLabel10)
                    .addComponent(searchBtn))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salaryLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(deptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deptLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EmployeeRd)
                                        .addComponent(budgetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(budgetLbl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EngineerRd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConsultantRd))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hoursTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hoursLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManagerRd))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rateLbl)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirectorRd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(viewAllBtn))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(searchBtn))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void EmployeeRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeRdActionPerformed
        // TODO add your handling code here:
        salaryTxt.setVisible(false);
        deptTxt.setVisible(false);
        budgetTxt.setVisible(false);
        
        hoursTxt.setVisible(false);
        rateTxt.setVisible(false);
        
        salaryLbl.setVisible(false);
        deptLbl.setVisible(false);
        budgetLbl.setVisible(false);
        
        hoursLbl.setVisible(false);
        rateLbl.setVisible(false);
        
        
    }//GEN-LAST:event_EmployeeRdActionPerformed

    private void EngineerRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerRdActionPerformed
        // TODO add your handling code here:
        
        salaryTxt.setVisible(true);
        deptTxt.setVisible(false);
        budgetTxt.setVisible(false);
        
        hoursTxt.setVisible(false);
        rateTxt.setVisible(false);
        
        salaryLbl.setVisible(true);
        deptLbl.setVisible(false);
        budgetLbl.setVisible(false);
        
        hoursLbl.setVisible(false);
        rateLbl.setVisible(false);
    }//GEN-LAST:event_EngineerRdActionPerformed

    private void ConsultantRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultantRdActionPerformed
        // TODO add your handling code here:
        
        salaryTxt.setVisible(false);
        deptTxt.setVisible(false);
        budgetTxt.setVisible(false);
        
        hoursTxt.setVisible(true);
        rateTxt.setVisible(true);
        
        salaryLbl.setVisible(false);
        deptLbl.setVisible(false);
        budgetLbl.setVisible(false);
        
        hoursLbl.setVisible(true);
        rateLbl.setVisible(true);
    }//GEN-LAST:event_ConsultantRdActionPerformed

    private void ManagerRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerRdActionPerformed
        // TODO add your handling code here:
        salaryTxt.setVisible(true);
        deptTxt.setVisible(true);
        budgetTxt.setVisible(false);
        
        hoursTxt.setVisible(false);
        rateTxt.setVisible(false);
        
        salaryLbl.setVisible(true);
        deptLbl.setVisible(true);
        budgetLbl.setVisible(false);
        
        hoursLbl.setVisible(false);
        rateLbl.setVisible(false);
    }//GEN-LAST:event_ManagerRdActionPerformed

    private void DirectorRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectorRdActionPerformed
        // TODO add your handling code here:
        
        salaryTxt.setVisible(true);
        deptTxt.setVisible(true);
        budgetTxt.setVisible(true);
        
        hoursTxt.setVisible(false);
        rateTxt.setVisible(false);
        
        salaryLbl.setVisible(true);
        deptLbl.setVisible(true);
        budgetLbl.setVisible(true);
        
        hoursLbl.setVisible(false);
        rateLbl.setVisible(false);
    }//GEN-LAST:event_DirectorRdActionPerformed

    private void salaryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryTxtActionPerformed

    private void deptTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptTxtActionPerformed

    private void budgetTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgetTxtActionPerformed

    private void hoursTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursTxtActionPerformed

    private void rateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTxtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
        name = nameTxt.getText();
        try {
            empId = Integer.parseInt(idTxt.getText());

            for(int i = 0; i < empList.size();i++){
                if(empList.get(i).getName().equalsIgnoreCase(name) && empList.get(i).getId() == empId){

                    confDialog = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete "+empList.get(i).getName()+"?");

                    if(confDialog == JOptionPane.YES_OPTION) {
                        empList.remove(i);
                    }
                }
            }
            
            saveData(empList);
            clearFields();
            
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Please enter an Employee ID.");
        }
            
        saveData(empList);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        name = nameTxt.getText();
        try {
            empId = Integer.parseInt(idTxt.getText());

            if(EmployeeRd.isSelected()) {
                type="Employee";
                Employee emp = new Employee(name,empId);
                empList.add(emp);
                JOptionPane.showMessageDialog(null, type+" added successfully.");
            } else if(EngineerRd.isSelected()) {
                type="Engineer";
                salary=Double.parseDouble(salaryTxt.getText());
                Engineer emp = new Engineer(name, empId,salary);
                empList.add(emp);
                JOptionPane.showMessageDialog(null, type+" added successfully.");
            } else if(ConsultantRd.isSelected()) {
                type="Consultant";
                hours=Integer.parseInt(hoursTxt.getText());
                rate=Double.parseDouble(rateTxt.getText());
                Consultant emp = new Consultant(name,empId,hours,rate);
                empList.add(emp);
                JOptionPane.showMessageDialog(null, type+" added successfully.");
            } else if(ManagerRd.isSelected()) {
                type="Manager";
                salary=Double.parseDouble(salaryTxt.getText());
                dept=deptTxt.getText();
                Manager emp = new Manager(name, empId, salary, dept);
                empList.add(emp);
                JOptionPane.showMessageDialog(null, type+" added successfully.");
            } else if(DirectorRd.isSelected()) {
                type="Director";
                salary=Double.parseDouble(salaryTxt.getText());
                dept=deptTxt.getText();
                budget=Double.parseDouble(budgetTxt.getText());
                Director emp = new Director(name, empId, salary, dept,budget);
                empList.add(emp);
                JOptionPane.showMessageDialog(null, type+" added successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Please select a type.");
            }
            
            saveData(empList);
            clearFields();
            
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Please enter an Employee ID.");
        }
        
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void viewAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllBtnActionPerformed
        // TODO add your handling code here:
    
        for(int i = 0; i < empList.size();i++){
            JOptionPane.showMessageDialog(null,empList.get(i).getDetails());
        }
        
    }//GEN-LAST:event_viewAllBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        
        searchList = new ArrayList<Employee>();
        
        name = nameTxt.getText();
        try {
            empId = Integer.parseInt(idTxt.getText());
        } catch(NumberFormatException e) {
            empId = -1;
            System.out.println(e);
        }
            System.out.println(empId);
        for(int i = 0; i < empList.size(); i++) {
            if(empList.get(i).getName().equalsIgnoreCase(name) || empList.get(i).getId() == empId) {
                searchList.add(empList.get(i));
            }
        }
        confDialog=JOptionPane.showConfirmDialog(null,searchList.size()+" records found. \nTo show results press Yes.");
        if(confDialog == JOptionPane.YES_OPTION) {
            for(int j = 0; j < searchList.size(); j++) {
                JOptionPane.showMessageDialog(null,searchList.get(j).getDetails());     
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeGUI().setVisible(true);
            }
        });
    }
    
    private static ArrayList<Employee> getData(){
        
        ArrayList<Employee> empList;
        
        try {
            File file = new File("database.DAT");
            FileInputStream fStream = new FileInputStream(file);
            ObjectInputStream oStream = new ObjectInputStream(fStream);
            
            empList = (ArrayList<Employee>) oStream.readObject();
               
        } catch(FileNotFoundException e) {
            empList = null;
            System.out.println(e);
        } catch(IOException ex) {
            empList = null;
            System.out.println(ex);
        } catch(ClassNotFoundException exc) {
            empList = null;
            System.out.println(exc);
        }
        
        return empList;   
    }
    
    private static void saveData(ArrayList<Employee> employeeList) {
    
       try {
            File file = new File("database.DAT");
            FileOutputStream fStream = new FileOutputStream(file);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(employeeList);
            
        } catch(FileNotFoundException e) {
            System.out.println(e);
        } catch(IOException ex) {
            System.out.println(ex);
        }
        
    }
    
    private void clearFields(){
    
        nameTxt.setText("");
        idTxt.setText("");
        salaryTxt.setText("");
        deptTxt.setText("");
        budgetTxt.setText("");
        hoursTxt.setText("");
        rateTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ConsultantRd;
    private javax.swing.JRadioButton DirectorRd;
    private javax.swing.JRadioButton EmployeeRd;
    private javax.swing.JRadioButton EngineerRd;
    private javax.swing.JRadioButton ManagerRd;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel budgetLbl;
    private javax.swing.JTextField budgetTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deptLbl;
    private javax.swing.JTextField deptTxt;
    private javax.swing.ButtonGroup empBtnGroup;
    private javax.swing.JLabel hoursLbl;
    private javax.swing.JTextField hoursTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel rateLbl;
    private javax.swing.JTextField rateTxt;
    private javax.swing.JLabel salaryLbl;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton viewAllBtn;
    // End of variables declaration//GEN-END:variables
}
