/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulesappnew;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefan
 */
public class ModulesGUI extends javax.swing.JFrame {
    private String name,lecturer,lectureday,tutorialday,labday;
    private ArrayList<Module> mList;
    
    
    /**
     * Creates new form ModulesGUI
     */
    public ModulesGUI() {
        initComponents();
        
        name ="";
        lecturer="";
        lectureday="";
        tutorialday="";
        labday="";
        
        mList = new ArrayList<>();
        
        tutorialdayLbl.setVisible(false);
        labdayLbl.setVisible(false);
        
        tutorialdayTxt.setVisible(false);
        labdayTxt.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGrp = new javax.swing.ButtonGroup();
        headingLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        lecturerTxt = new javax.swing.JTextField();
        lecturerLbl = new javax.swing.JLabel();
        lecturedayTxt = new javax.swing.JTextField();
        lecturedayLbl = new javax.swing.JLabel();
        simpleRd = new javax.swing.JRadioButton();
        businessRd = new javax.swing.JRadioButton();
        technicalRd = new javax.swing.JRadioButton();
        typeLbl = new javax.swing.JLabel();
        tutorialdayLbl = new javax.swing.JLabel();
        tutorialdayTxt = new javax.swing.JTextField();
        labdayTxt = new javax.swing.JTextField();
        labdayLbl = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headingLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        headingLbl.setText("Enter a new Model");

        nameLbl.setText("Module Name:");

        lecturerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerTxtActionPerformed(evt);
            }
        });

        lecturerLbl.setText("Lecturer:");

        lecturedayLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lecturedayLbl.setText("Lecture day:");

        typeGrp.add(simpleRd);
        simpleRd.setText("Simple");
        simpleRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleRdActionPerformed(evt);
            }
        });

        typeGrp.add(businessRd);
        businessRd.setText("Business");
        businessRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessRdActionPerformed(evt);
            }
        });

        typeGrp.add(technicalRd);
        technicalRd.setText("Technical");
        technicalRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicalRdActionPerformed(evt);
            }
        });

        typeLbl.setText("Type:");

        tutorialdayLbl.setText("Tutorial day:");

        labdayLbl.setText("Lab day:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display Last");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        listBtn.setText("List All");
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpleRd)
                            .addComponent(businessRd)
                            .addComponent(technicalRd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lecturedayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lecturerLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTxt)
                            .addComponent(lecturerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(lecturedayTxt))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labdayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tutorialdayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tutorialdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labdayTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutorialdayLbl)
                    .addComponent(tutorialdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturerLbl)
                    .addComponent(lecturerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labdayLbl)
                    .addComponent(labdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturedayLbl)
                    .addComponent(lecturedayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpleRd)
                    .addComponent(typeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(businessRd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(technicalRd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(displayBtn)
                    .addComponent(listBtn)
                    .addComponent(searchBtn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpleRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleRdActionPerformed
        // TODO add your handling code here:
        tutorialdayLbl.setVisible(false);
        labdayLbl.setVisible(false);
        
        tutorialdayTxt.setVisible(false);
        labdayTxt.setVisible(false);
    }//GEN-LAST:event_simpleRdActionPerformed

    private void businessRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessRdActionPerformed
        // TODO add your handling code here:
        tutorialdayLbl.setVisible(true);
        labdayLbl.setVisible(false);
        
        tutorialdayTxt.setVisible(true);
        labdayTxt.setVisible(false);
    }//GEN-LAST:event_businessRdActionPerformed

    private void lecturerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerTxtActionPerformed

    private void technicalRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicalRdActionPerformed
        // TODO add your handling code here:
        tutorialdayLbl.setVisible(false);
        labdayLbl.setVisible(true);
        
        tutorialdayTxt.setVisible(false);
        labdayTxt.setVisible(true);
    }//GEN-LAST:event_technicalRdActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        name = nameTxt.getText();
        lecturer = lecturerTxt.getText();
        lectureday = lecturedayTxt.getText();
        Module module;
        
        if((!simpleRd.isSelected() && !businessRd.isSelected() && !technicalRd.isSelected()) || name.equals("") || lecturer.equals("") || lectureday.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a name, a lecturer, a lecture day and select a Module type.");
       
       // } else if(businessRd.isSelected() && tutorialdayTxt.getText().equals("")){
        } else if((businessRd.isSelected() && tutorialdayTxt.getText().equals("")) || (technicalRd.isSelected() && labdayTxt.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Please enter all required fields. A Tutorial Day for Business Modules and a Lab Day for Technical Modules.");
        } else {
        
            if(simpleRd.isSelected()){
                //Module
                module = new Module(name, lecturer, lectureday);
            } else if(businessRd.isSelected()) {
                //Business Module
                tutorialday = tutorialdayTxt.getText();
                module = new BusinessModule(name, lecturer, lectureday, tutorialday);
            } else {
                //Technical Module
                labday = labdayTxt.getText();
                module = new TechnicalModule(name, lecturer, lectureday, labday);
            }
            
            mList.add(module);
            
            try{
                File file = new File("modules.DAT");
                FileOutputStream fStream = new FileOutputStream(file);
                ObjectOutputStream oStream = new ObjectOutputStream(fStream);
               
                oStream.writeObject(mList);
                clearFields();
                JOptionPane.showMessageDialog(null, "You have entered a new Module!");
                
            } catch(FileNotFoundException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
            } catch(IOException ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
            }
            
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        //Display Last Item
        try {
            File file = new File("modules.DAT");
            FileInputStream fStream = new FileInputStream(file);
            ObjectInputStream oStream = new ObjectInputStream(fStream);

            mList = (ArrayList<Module>) oStream.readObject();

            Module module;
            module = mList.get(mList.size()-1);

            if(module instanceof BusinessModule) {

               BusinessModule bm = (BusinessModule) mList.get(mList.size()-1);
               JOptionPane.showMessageDialog(null,"Module Name: "+bm.getName()+"\nLecturer: "+bm.getLecturer()+"\nLecture Day: "
                        +bm.getLectureday()+"\nTutorial Day: "+bm.getTutorialday());

            } else if(module instanceof TechnicalModule) {
                TechnicalModule tm = (TechnicalModule) mList.get(mList.size()-1);
                JOptionPane.showMessageDialog(null,"Module Name: "+tm.getName()+"\nLecturer: "+tm.getLecturer()+"\nLecture Day: "
                        +tm.getLectureday()+"\nLab Day: "+tm.getLabday());
            } else {
                JOptionPane.showMessageDialog(null,"Module Name: "+module.getName()+"\nLecturer: "+module.getLecturer()+"\nLecture Day: "
                        +module.getLectureday());
            }
        } catch (FileNotFoundException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        } catch(IOException ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        } catch(ClassNotFoundException exe){
                System.out.println(exe);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
        //Display Last Item
        try {
            File file = new File("modules.DAT");
            FileInputStream fStream = new FileInputStream(file);
            ObjectInputStream oStream = new ObjectInputStream(fStream);

            mList = (ArrayList<Module>) oStream.readObject();
            
            for(int i = 0; i < mList.size(); i++) {
                Module module;
                module = mList.get(i);

                if(module instanceof BusinessModule) {

                   BusinessModule bm = (BusinessModule) mList.get(i);
                   JOptionPane.showMessageDialog(null,"Module Name: "+bm.getName()+"\nLecturer: "+bm.getLecturer()+"\nLecture Day: "
                            +bm.getLectureday()+"\nTutorial Day: "+bm.getTutorialday());

                } else if(module instanceof TechnicalModule) {
                    TechnicalModule tm = (TechnicalModule) mList.get(i);
                    JOptionPane.showMessageDialog(null,"Module Name: "+tm.getName()+"\nLecturer: "+tm.getLecturer()+"\nLecture Day: "
                            +tm.getLectureday()+"\nLab Day: "+tm.getLabday());
                } else {
                    JOptionPane.showMessageDialog(null,"Module Name: "+module.getName()+"\nLecturer: "+module.getLecturer()+"\nLecture Day: "
                            +module.getLectureday());
                }
            }
        } catch (FileNotFoundException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        } catch(IOException ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        } catch(ClassNotFoundException exe){
                System.out.println(exe);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        }
    }//GEN-LAST:event_listBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File("modules.DAT");
            FileInputStream fStream = new FileInputStream(file);
            ObjectInputStream oStream = new ObjectInputStream(fStream);

            mList = (ArrayList<Module>) oStream.readObject();
            String search;
            search = JOptionPane.showInputDialog(null, "Enter your Module name, Lecturer or Lecture Day to search!");
            
            for(int i = 0; i < mList.size(); i++) {
                Module module;
                module = mList.get(i);
                
                if(module.getName().indexOf(search) != -1 || module.getLecturer().indexOf(search) != -1 || module.getLectureday().indexOf(search) != -1) {
                    
                   if(module instanceof BusinessModule) {
                        BusinessModule bm = (BusinessModule) mList.get(i);
                        JOptionPane.showMessageDialog(null,"Module Name: "+bm.getName()+"\nLecturer: "+bm.getLecturer()+"\nLecture Day: "
                                +bm.getLectureday()+"\nTutorial Day: "+bm.getTutorialday());

                    } else if(module instanceof TechnicalModule) {
                        TechnicalModule tm = (TechnicalModule) mList.get(i);
                        JOptionPane.showMessageDialog(null,"Module Name: "+tm.getName()+"\nLecturer: "+tm.getLecturer()+"\nLecture Day: "
                                +tm.getLectureday()+"\nLab Day: "+tm.getLabday());
                    } else {
                        JOptionPane.showMessageDialog(null,"Module Name: "+module.getName()+"\nLecturer: "+module.getLecturer()+"\nLecture Day: "
                                +module.getLectureday());
                    }                    
                
                }
            }
        } catch (FileNotFoundException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        } catch(IOException ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        } catch(ClassNotFoundException exe){
                System.out.println(exe);
                JOptionPane.showMessageDialog(null, "An unexpected error occurred please try again!");
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModulesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModulesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModulesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModulesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModulesGUI().setVisible(true);
            }
        });
    }
    
    private void clearFields(){
        nameTxt.setText("");
        lecturerTxt.setText("");
        lecturedayTxt.setText("");
        tutorialdayTxt.setText("");
        labdayTxt.setText("");
        
        simpleRd.setSelected(false);
        businessRd.setSelected(false);
        technicalRd.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton businessRd;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JLabel labdayLbl;
    private javax.swing.JTextField labdayTxt;
    private javax.swing.JLabel lecturedayLbl;
    private javax.swing.JTextField lecturedayTxt;
    private javax.swing.JLabel lecturerLbl;
    private javax.swing.JTextField lecturerTxt;
    private javax.swing.JButton listBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JRadioButton simpleRd;
    private javax.swing.JRadioButton technicalRd;
    private javax.swing.JLabel tutorialdayLbl;
    private javax.swing.JTextField tutorialdayTxt;
    private javax.swing.ButtonGroup typeGrp;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
